### ISSUE TITLE
Incorrect alpha handling in the encoder

### ISSUE THREAD

**Issue by mzgreen** [saharNooby/qoi-java#2]
Hey,

I have noticed that there is a bug in the encoder. Specifically https://github.com/saharNooby/qoi-java/blob/main/src/main/java/me/saharnooby/qoi/QOIEncoder.java#L174 here. The original C implementation is using signed arithmetic in this place https://github.com/phoboslab/qoi/blob/master/qoi.h#L465

This may not seem like a big issue since the encoding and decoding seems to be working fine but if you take a .qoi file, decode and then encode it back with this library then the resulting file will not always be identical to the original .qoi file.

You can verify this by performing a test like this:
1. Download test files https://qoiformat.org/qoi_test_images.zip
2. For each test file run a test:
    - decode the file
    - encode back the decoded file
    - compare the resulting file with the original test file byte by byte

**Comment by saharNooby** [comment]
Thanks for the report, will look into it soon!

When developing, I've noticed that encoded images do not always match those produced by reference encoder, but decided to not investigate since tests pass. Since you have pointed to the specific line, now it will be easier to investigate.

**Comment by mzgreen** [comment]
Yeah debugging such issues is not straightforward but it's worth fixing since bugs like this may affect the size of the files produced by the encoder.

**Comment by saharNooby** [comment]
Fixed in 1.2.1, all test images now match when encoded by qoi-java.
